default_language_version:
  python: python3.7

repos:
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [--remove]
      - id: requirements-txt-fixer
      - id: mixed-line-ending
        args: [--fix=crlf]
  - repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
      - id: black
        args: [--py36, src, sql]
